# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "delayed_job-monitor"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Guterl"]
  s.date = "2011-12-30"
  s.description = "A tool for monitoring the health of a delayed_job work queue"
  s.email = "michael@diminishing.org"
  s.executables = ["delayed_job_monitor"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/delayed_job_monitor",
    "delayed_job-monitor.gemspec",
    "lib/delayed_job/monitor.rb",
    "spec/delayed_job-monitor_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/recruitmilitary/delayed_job-monitor"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Monitor the health of your delayed_job work queue"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_runtime_dependency(%q<sequel>, ["~> 3.12.1"])
      s.add_runtime_dependency(%q<pony>, ["~> 1.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<sequel>, ["~> 3.12.1"])
      s.add_dependency(%q<pony>, ["~> 1.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<sequel>, ["~> 3.12.1"])
    s.add_dependency(%q<pony>, ["~> 1.0.0"])
  end
end

